### ISSUE TITLE
please bump version

### ISSUE THREAD

**Issue by nifgraup** [emailjs/emailjs-imap-handler#15]

**Comment by andris9** [comment]
@nifgraup would do it myself but I think that only @felixhammerl has permissions to publish to npm. Btw are you actually using these libraries for something?

**Comment by felixhammerl** [comment]
done. i thought @andris9 should have npm rights, too. apparently not. will add @andris9 later to all emailjs projects :)

**Comment by nifgraup** [comment]
Thanks, yes, we are using emailjs for an upcoming mail client for Vivaldi Browser and have found it pleasant to work with.

We'll continue to submit pull requests for issues that occasionally arise, the latest being https://github.com/emailjs/emailjs-imap-client/pull/116

**Comment by andris9** [comment]
Neat! I recently added a new feature to [Mailtrain](https://github.com/andris9/mailtrain) that was also requested by someone from Vivaldi.

Regards to emailjs, I think you are a year or two too late. Felix has kept this project on life support but that's more or less about it, all the original contributors have moved on. I've been working on server side email components like Mailtrain or [ZoneMTA](https://github.com/zone-eu/zone-mta), the other guys have been doing their things, not much being related to email protocols in front-end as far as I'm aware of.
