### ISSUE TITLE
Parser fails on [Airmail] folder

### ISSUE THREAD

**Issue by ltgorm** [emailjs/emailjs-imap-handler#16]
When using Airmail account the root folder name is enclosed in brackets: "[Airmail]".
Trying to connect to such an account gives error:
`Unexpected section start char [ at position 7` at emailjs-imap-parser.js (422)

Putting in a debug log to log out the command that is failing reveals:
` (\HasChildren) "." Trash.[Airmail]`

**Comment by andris9** [comment]
I once rewrote the handler for another IMAP project that required more lax handling and I think that the modified version was able to manage such names. The modified code can be seen [here](https://github.com/andris9/imap-core/tree/master/lib/handler)

**Comment by ltgorm** [comment]
Thanks for the swift response @andris. But your modified code does not behave better on this example. It turns out that the hierarchy separator set on the mail server affects the behavior. Trash.[Airmail] fails while Trash/[Airmail] parses correctly. Furthermore the type of the parsed object will also be different based on the separator. INBOX/Jira is parsed as type STRING while Trash.Ble is parsed as type ATOM. I am trying to find a solution but all input appreciated.

**Comment by nifgraup** [comment]
Merged to master. Btw. @andris9, the laxed handling is still within the IMAP spec.
