### ISSUE TITLE
Error parsing IMAP server response

### ISSUE THREAD

**Issue by rickhall** [emailjs/emailjs-imap-handler#20]
I am issuing a query for multiple body parts, basically something like this:
```
t uid fetch 585599 (body.peek[1.1] body.peek[1.2])
```
This results in a response like this:

```
* 126015 FETCH (UID 585599 BODY[1.2] {0}
 BODY[1.1] {0}
)
t OK Success
```
This is the correct response, since the message has two alternative message bodies, both of which are empty. But imapHandler.parser() throws a parsing error when passing it the following string:
```
* 126015 FETCH (UID 585599 BODY[1.2] {0}\r\n BODY[1.1] {0}
```
I have not dug any deeper at this point.

**Comment by andris9** [comment]
The string is missing "\r\n)" from the end. Did it get lost from copy-paste or is it really missing?

**Comment by rickhall** [comment]
The usage of imapHandler was in emailjs-imap-client and I simply added a logger statement in the following code snippet to see what the actual command was that failed parsing:
```
            try {
                response = imapHandler.parser(command.trim());
                this.logger.debug('S:', () => imapHandler.compiler(response, false, true));
            } catch (e) {
this.logger.error("Cannot parse " + command); // RSH
                this.logger.error('Error parsing imap command!', response);
                return this._onError(e);
            }
```
What I pasted is what appeared in my console from my logger impl for emailjs-imap-client:
```
[DOWNLOADER] ERROR  ["Cannot parse * 126015 FETCH (UID 585599 BODY[1.2] {0}\r\n BODY[1.1] {0}"]
```
So, it looks like it is missing. However, if I manually perform this query via ssh is:
```
t uid fetch 585599 (body.peek[1.1] body.peek[1.2])
* 126015 FETCH (UID 585599 BODY[1.2] {0}
 BODY[1.1] {0}
)
t OK Success
```
So, it seems that the server sends it, but for some reason it is getting lost. Any clues?

**Comment by rickhall** [comment]
Just for more information, I added some addition tracing to emailjs-imap-client-imap.js in the loop where it is parsing incoming commands:
```
    Imap.prototype._parseIncomingCommands = function(commands) {
        for (var command of commands) {
this.logger.debug("Trying to parse " + JSON.stringify(command)); // RSH
            this._clearIdle();
            ...
```
From my trace I see:
```
[DOWNLOADER] DEBUG  ["Trying to parse \"* 126015 FETCH (UID 585599 BODY[1.2] {0}\\r\\n BODY[1.1] {0}\""]
[DOWNLOADER] ERROR  ["Cannot parse * 126015 FETCH (UID 585599 BODY[1.2] {0}\r\n BODY[1.1] {0}"]
```
So, for some reason the queued command seems to be truncated.

**Comment by rickhall** [comment]
Is it possible that parsing code in Imap.prototype._iterateIncomingBuffer is not expecting multiple body parts in a single query?

I see at the beginning of the function that this._incomingBuffers looks correct:
```
[DOWNLOADER] DEBUG  ["Incoming buffers 0: * 126015 FETCH (UID 585599 BODY[1.2] {0}\r\n BODY[1.1] {0}\r\n)\r\n"]
```
However, down around line 472:
```
          if (this._literalRemaining === 0 && i < buf.length) {
              const LFidx = buf.indexOf(LINE_FEED, i);
```
It looks for a linefeed, which it seems to assume is the end of the response, but in this case it is actually the end of the second body part. It finds the line feed at LFidx === 57, which corresponds to just before the trailing "\r\n)". It creates the command minus those trailing characters and pushes the remaining bytes back into this._incomingBuffers.

I'm not sure if I understand enough of what is going on in there to fix this, but hopefully it is enough to help you fix it.

**Comment by rickhall** [comment]
Trying to understand what is happening here a little more, it does appear that the code doesn't handle multiple parts correctly. It looks for the left curly brace and effectively reads the number to get the size of this._literalRemaining, which in this case it is {0} for the first body part (even though the second body part is still in the buffer).

Then it goes on like I describe above by finding the next line feed and assuming it is the end of the response.

It's not clear to me if size {0} is the key issue here or not, since I am performing this query repeatedly and it doesn't error on each message. Essentially, I'm querying the text and html alternatives of the message body, so I'm guessing that I do see cases with multiple parts but with actual content.

So, perhaps its just the edge case of the size being {0}.

**Comment by rickhall** [comment]
It doesn't appear to be related to size {0}. I tried some more examples and it threw an exception on a message with content in its text/html alternatives. The same type of error where the command is truncated in the middle of some message content.

So, the code appears to not be able to handle parsing the response to a query like "(body.peek[X] body.peek[Y])".

**Comment by nifgraup** [comment]
Adding the following test case to emailjs-imap-client-imap-test.js would catch the error
```
            it('Test case for https://github.com/emailjs/emailjs-imap-handler/issues/20', () => {
                appendIncomingBuffer('* 126015 FETCH (UID 585599 BODY[1.2] {0}\r\n BODY[1.1] {0}\r\n)\r\n');
                var iterator = client._iterateIncomingBuffer();
                expect(String.fromCharCode.apply(null, iterator.next().value)).to.equal ('* 126015 FETCH (UID 585599 BODY[1.2] {0}\r\n BODY[1.1] {0}\r\n)');
            });```

**Comment by rickhall** [comment]
Any progress on this?

**Comment by nifgraup** [comment]
No, I'm not using emailjs-imap-client in such a way that I have been hit by this, so it hasn't been pressing. Can you give it a try?

**Comment by rickhall** [comment]
Yeah, I've been trying to make heads or tails out of this function for a while now. It still has me confused, but I'm still poking around. If I come up with anything, I'll report back.

**Comment by rickhall** [comment]
I think I can close this issue, since the issue doesn't appear to be with emailjs-imap-handler. I've submitted a PR against emailjs-imap-client to address this issue. The issue does appear to be related to zero-length literals. Unfortunately, I think there is yet another issue that I need to look into, because I am seeing errors with some non-zero-length literals too.

I'll look into that some more and open another issue when and where appropriate.
